site_name: My Docs

nav:
  - Home: index.md
  - Python:
    - Funções: python/funcoes.md
    - Instalações: python/instalacao.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  favicon: img/favicon.svg
  name: material
  palette:
      primary: black
      accent: indigo
  font:
    text: Ubuntu
    code: Ubuntu Mono 
